# System Codes
SC_VAT_CALCULATION_METHOD = 'VAT Calculation Method'
SC_DISCOUNT_TYPE = 'Discount Type'
SC_INVOICE_STATUS = 'Invoice Status'
SC_PAYMENT_METHOD = 'Payment Method'



# System Code Details
SCD_CALCULATION_METHOD_BEFORE_TAX = 'Before Tax'
SCD_CALCULATION_METHOD_AFTER_TAX = 'After Tax'
SCD_DISCOUNT_TYPE_PERCENTAGE = 'Percentage'
SCD_DISCOUNT_TYPE_FIXED = 'Fixed'
SCD_INVOICE_STATUS_DRAFT = 'Draft'
SCD_INVOICE_STATUS_SENT = 'Sent'
SCD_INVOICE_STATUS_PAID = 'Paid'
SCD_PAYMENT_METHOD_CASH = 'Cash'
SCD_PAYMENT_METHOD_CREDIT_CARD = 'M-Pesa'