# Generated by Django 5.1.6 on 2025-02-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='additional_info',
            new_name='description',
        ),
    ]
