# Generated by Django 5.1.6 on 2025-02-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
