# Generated by Django 5.1.6 on 2025-02-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_calculation_method_invoice_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='calculation_method',
            new_name='vat_calculation_method',
        ),
    ]
