# Generated by Django 5.1.6 on 2025-02-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_discount_value_invoice_vat_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
