# Generated by Django 5.1.6 on 2025-02-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoice_discount_value_alter_invoice_vat_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='vat_calculation_method',
        ),
    ]
